version: "3.6"

services:
    pooling:
        build: .
        ports:
        - "9091:9091"
        environment:
        - PORT=9091


    acceptance:
      image: cabify/challenge:latest
      #command: ["tail", "-f", "/dev/null"]
      command: /harness --address http://pooling:9091 acceptance
      depends_on:
        - pooling
