version: "3.6"

services:
    pooling:
        build: .
        ports:
        - "8080:8080"

    acceptance:
      image: cabify/challenge:latest
      #command: ["tail", "-f", "/dev/null"]
      command: /harness --address http://pooling:8080 acceptance
      depends_on:
        - pooling
